version: '3.8'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ml_football
    ports:
      - '8001:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    container_name: postgres_database

  updater:
    build: 
      context: .
      dockerfile: Dockerfile-updater
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_HOST=db:5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - ./data:/app/data
