FROM python:3.10-slim

WORKDIR /app
COPY etl/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt
RUN mkdir /app/data/

COPY etl/ ./etl
COPY database/ ./database/

RUN unset https_proxy

CMD ["python3", "-m" , "etl.update"]