version: '3.8'
services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ml_football
    ports:
      - '8001:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
    container_name: postgres_database
