name: Deploy app

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Update codebase and deploy
      run: |
        whoami
        cd /home/rpi_user/git_repos/ml_football
        git fetch origin main
        git pull origin main
        docker compose down
        docker compose up -d
