name: Deploy app

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Change dir
      run: cd /home/rpi_user/git_repos/ml_football
    - name: Update codebase
      run: |
        sudo git fetch origin main
        sudo git pull origin main
    - name: Deploy
      run: |
        docker compose down
        docker compose up -d
