name: Quality

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: Pylint
      run: |
        pylint . --recursive=y

