name: Testing

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  ETL:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r etl/requirements.txt
    - if: github.ref == 'refs/heads/dev'
      name: test dev
      run: pytest --cov=etl --cov-fail-under=50
    - if: github.ref == 'refs/heads/main'
      name: test main
      run: pytest --cov=etl --cov-fail-under=85

