name: Testing

on:
  push:
  pull_request:
    branches: [ main, dev ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: pytest 
      if: github.ref == 'refs/heads/dev'
      run: pytest --cov --cov-fail-under=50
      if: github.ref == 'refs/heads/main'
      run: pytest --cov --cov-fail-under=85

